# render.yaml
services:
  - type: cron
    name: youtube-tracker-cron
    schedule: "30 20 * * *"  # Runs at 20:30 UTC daily
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    repo: https://github.com/yourusername/youtube_tracker  # Replace with your GitHub repo URL
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: youtube-tracker-db
          property: connectionString

databases:
  - name: youtube-tracker-db
    databaseName: youtube_tracker
    plan: free

