# render.yaml

services:
  - type: cron
    name: youtube-tracker-cron
    schedule: "@hourly"  # Runs the script every hour
    command: "python app.py"
    env: python
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: ""
    repo: https://github.com/yourusername/youtube_tracker  # Replace with your GitHub repo URL
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: youtube-tracker-db
          property: connectionString
  - type: database
    name: youtube-tracker-db
    databaseName: youtube_tracker
    starterPlan: starter  # Use the free tier or upgrade as needed
